services:

  postgres:
    container_name: postgres
    build:
      context: ./postgres/
      dockerfile: Dockerfile
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_DB=datasync
      - POSTGRES_USER=datasync
      - POSTGRES_PASSWORD=ra5hoxetRami5
      - POSTGRES_PORT=5432
    volumes:
      - postgresvolume:/var/lib/postgresql/data

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.5.3
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticvolume:/usr/share/elasticsearch/data

  logstash:
    container_name: logstash
    build:
      context: ./logstash/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - CONFIG_SUPPORT_ESCAPE=true
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
      - postgres
    volumes:
      - logstashvolume:/usr/share/logstash/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: your_email@example.com
      PGADMIN_DEFAULT_PASSWORD: your_password
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadminvolume:/var/lib/pgadmin

volumes:
  postgresvolume:
  elasticvolume:
  logstashvolume:
  pgadminvolume:
